name: hhop
favicon: null
layout_spectrum: 0.9006566249299794
typography_spectrum: 0.9707914551254362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c55b5e'
    - '#66656b'
    - '#46464e'
    - '#29132c'
    - '#bc916f'
  brandStrength: 0.625
  lightness: 0.81236926256679
  saturation: 0.009194670943543315
  rhythmicContrast: 0.8433156807441264
purpose: []
