name: hhop
favicon: null
layout_spectrum: 0.9006566249299794
typography_spectrum: 0.9707914551254362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f065'
    - '#9b7b8e'
    - '#a8d8d7'
    - '#475e7b'
    - '#f51b76'
  brandStrength: 0.625
  lightness: 0.81236926256679
  saturation: 0.009194670943543315
  rhythmicContrast: 0.8433156807441264
purpose: []
