name: hhop
favicon: null
layout_spectrum: 0.9006566249299794
typography_spectrum: 0.9707914551254362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4007035191170871
  lightness: 0.81236926256679
  saturation: 0.009194670943543315
  rhythmicContrast: 0.8433156807441264
purpose: []
